CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100) NOT NULL UNIQUE,
    name  varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(100) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation        VARCHAR(20000) NOT NULL,
    title             VARCHAR(10000) NOT NULL,
    description       VARCHAR(20000) NOT NULL,
    state             VARCHAR(500)   NOT NULL,
    created           TIMESTAMP               DEFAULT NOW(),
    published         TIMESTAMP,
    start_date        TIMESTAMP      NOT NULL,
    initiator         INTEGER REFERENCES users (id) ON DELETE CASCADE,
    lat               NUMERIC(6, 2)  NOT NULL,
    lon               NUMERIC(6, 2)  NOT NULL,
    category          BIGINT         REFERENCES categories (id) ON DELETE SET NULL,
    paid              BOOLEAN                 DEFAULT FALSE,
    moderation        BOOLEAN                 DEFAULT FALSE,
    participant_limit INTEGER        NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS requests
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event   INTEGER REFERENCES events (id) ON DELETE CASCADE,
    author  INTEGER REFERENCES users (id) ON DELETE CASCADE,
    state   VARCHAR(32) NOT NULL,
    created TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event       INTEGER REFERENCES events (id) ON DELETE CASCADE,
    compilation INTEGER REFERENCES compilations (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_text VARCHAR(10000) NOT NULL,
    event        BIGINT REFERENCES events (id) ON DELETE CASCADE,
    author       BIGINT REFERENCES users (id) ON DELETE CASCADE,
    published    TIMESTAMP DEFAULT NOW()
);